#!/bin/bash
## Author:
#   Philip Newborough <corenominal@corenominal.org>
# Copyright:
#   © 2008 Philip Newborough <corenominal@corenominal.org>
# License:
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU Lesser General Public
#   License as published by the Free Software Foundation; either
#   version 2.1 of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public
#   License along with this library; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#   On Debian systems, the complete text of the GNU Lesser General Public
#   License V2.1 can be found in the file `/usr/share/common-licenses/LGPL-2.1'.
#-------------------------------------------------------------------------------
#
# Further edited by Mytchel Hammond, well it was basicly remade with the old
# version (http://crunchbanglinux.org/pastebin/235) as a reference
# 

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage:"
    echo "  rotate-wallpaper --path DIRECTORY"
    echo "    -h, --help"
    echo "          Shows this message and exits."
    echo "    -p [path to wallpapers], --path [path to wallpapers]"
    echo "          Set path to directory containing images."
    echo "    -t, --total"
    echo "          Return total number of images in wallpaper directory"
    echo "    -c, --count"
    echo "          Return current image number"
    echo "    -d, --restore-default-settings"
    echo "          Reset settings file to default"
    echo "    -f, --file"
    echo "          Return filepath of current wallpaper"
    echo "    -b, --back"
    echo "          Go to previose wallpaper"
    echo ""
    echo "Settings file located at ~/.config/rotate-wallpaper/settings"
    echo "You can change the directory that the wallpapers are picked from and the current wallpaper number"
    echo ""
    exit
fi



# Check for and do options ------------------------------------------------------

if [ ! -d ~/.config/rotate-wallpaper ]; then
    mkdir ~/.config/rotate-wallpaper
fi

if [ ! -f ~/.config/rotate-wallpaper/settings ]; then
    touch ~/.config/rotate-wallpaper/settings
    echo "Run again to rotate wallpaper"
    rotate-wallpaper -d
fi

if [ "$1" = "-p" ] || [ "$1" = "--path" ]; then
    echo "Setting wallpaper directory to $2"
    printf "current=0\ntotal=0\nwallpapers=$2" > ~/.config/rotate-wallpaper/settings
fi

. ~/.config/rotate-wallpaper/settings

if [ "$1" = "-d" ] || [ "$1" = "--restore-default-settings" ]; then
    printf "current=0\ntotal=0\nwallpapers=~/images/wallpapers" > ~/.config/rotate-wallpaper/settings
    echo "Made new settings file..."
    exit
fi

if [ "$1" = "-t" ] || [ "$1" = "--total" ]; then
    echo "$total"
    exit
fi

if [ "$1" = "-c" ] || [ "$1" = "--count" ]; then
    echo "$current"
    exit
fi

if [ "$1" = "-f" ] || [ "$1" = "--file" ]; then
    echo "$wallpaper_file"
    exit
fi

if [ ! -d $wallpapers ]; then
    echo "Oops! Specified directory does not exist."
    echo ""
    rotatewallpaper --help
    exit 1
fi

# Test location for images to use as wallpapers ---------------------------------------------- 

QUERY=""
if [ "$(ls $wallpapers/*.jpg 2> /dev/null)" ]; then
    QUERY="$QUERY$wallpapers/*.jpg "
fi

if [ "$(ls -l $wallpapers/*.png 2> /dev/null)" ]; then
    QUERY="$QUERY$wallpapers/*.png "
fi

if [ "$QUERY" = "" ];then
    echo "Oops! No images found within specified directory."
    echo ""
    rotatewallpaper --help
    exit 1
fi

# Get number of wallpapers -------------------------------------------------------------

NO_OF_WALLPAPERS=0
for file in $QUERY; do
    if [ ! -d "$file" ];then
	NO_OF_WALLPAPERS=$(( NO_OF_WALLPAPERS+1 ))
    fi
done



# Get number of new wallpaper and loop back to 0 if more than total -----------------------

NEW_WALLPAPER=$(( current+1 ))

if [ "$1" = "-b" ] || [ "$1" = "--back" ]; then
    NEW_WALLPAPER=$(( current-1 ))
fi

if [ $NEW_WALLPAPER -gt $NO_OF_WALLPAPERS ];then
    NEW_WALLPAPER=1
fi



# find and set wallpaper -------------------------------------------

wallpaper_file=1
CNT=1
for file in $QUERY; do
    if [ $CNT = $NEW_WALLPAPER ]; then
        if [ ! -d "$file" ];then
            FILE_TYPE=$(file -i "$file")

            if [ "$FILE_TYPE" = "$file: image/png; charset=binary" ] || [ "$FILE_TYPE" = "$file: image/jpeg; charset=binary" ]; then
                color="101010" 
                nitrogen --set-auto --set-color=$color "$file" 2> /dev/null
                wallpaper_file=${file}
            fi
        fi
    fi
    CNT=$(( CNT+1 ))
done

# save current wallpaper

printf "current=$NEW_WALLPAPER\ntotal=$NO_OF_WALLPAPERS\nwallpapers=$wallpapers\nwallpaper_file='$wallpaper_file'" > ~/.config/rotate-wallpaper/settings

setconkytextcolor

exit
