#!/bin/bash
## Author:
#   Philip Newborough <corenominal@corenominal.org>
# Copyright:
#   © 2008 Philip Newborough <corenominal@corenominal.org>
# License:
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU Lesser General Public
#   License as published by the Free Software Foundation; either
#   version 2.1 of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public
#   License along with this library; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#   On Debian systems, the complete text of the GNU Lesser General Public
#   License V2.1 can be found in the file `/usr/share/common-licenses/LGPL-2.1'.
#-------------------------------------------------------------------------------
#
# Further edited by Mytchel Hammond, well it was basicly remade with the old
# version (http://crunchbanglinux.org/pastebin/235) as a reference
# 

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Set wallpaper to random from directory"
    echo "Usage:"
    echo "  rotatewallpaper [options]"
    echo "    -h, --help"
    echo "          Shows this message and exits."
    echo "    -p [path to wallpapers], --path [path to wallpapers]"
    echo "          Set path to directory containing images."
    echo "    -s [image]"
    echo "          Set image as wallpaper."
    echo "    -t, --total"
    echo "          Return total number of images in wallpaper directory"
    echo "    -c, --count"
    echo "          Return current image number"
    echo "    -d, --restore-default-settings"
    echo "          Reset settings file to default"
    echo "    -f, --file"
    echo "          Return filepath of current wallpaper"
    echo "    -b, --back"
    echo "          Go to previous wallpaper"
    echo ""
    echo "Settings stored at ~/.config/rotatewallpaper/settings"
    echo ""
    exit
fi

settings=~/.config/rotatewallpaper/settings

function save() {
    echo "current=$1" > "$settings"
    echo "total=$2" >> "$settings"
    echo "wallpapers=$3" >> "$settings"
    echo "wallpaper_file='$4'" >> "$settings"
}

# Check for and do options ------------------------------------------------------

if [ ! -d ~/.config/rotatewallpaper ]; then
    mkdir ~/.config/rotatewallpaper
fi

if [ ! -f "$settings" ]; then
    touch "$settings"
    $0 -d
fi

if [ "$1" = "-p" ] || [ "$1" = "--path" ]; then
    echo "Setting wallpaper directory to $2"
    save 0 0 "$2" ''
fi

if [ "$1" = "-d" ] || [ "$1" = "--restore-default-settings" ]; then
    save 0 0 ~/images/wallpapers ''
    echo "Made new settings file..."
    exit
fi

. "$settings"

function setwall() {
    color="101010"
    nitrogen --set-auto --set-color=$color "$1" 2> /dev/null
    #feh --bg-fill "$1" 2> /dev/null
    save "$2" "$total" "$wallpapers" "$1"
}

if [ "$1" = "-t" ] || [ "$1" = "--total" ]; then
    echo "$total"
    exit
fi

if [ "$1" = "-c" ] || [ "$1" = "--count" ]; then
    echo "$current"
    exit
fi

if [ "$1" = "-f" ] || [ "$1" = "--file" ]; then
    echo "$wallpaper_file"
    exit
fi

if [ "$1" = "-s" ]; then
    setwall "$2" "0"
    exit
fi

if [ ! -d $wallpapers ]; then
    echo "Oops! Specified directory does not exist."
    echo ""
    $0 --help
    exit 1
fi

# Test location for images to use as wallpapers ---------------------------------------------- 

QUERY=""
QUERY="$QUERY$wallpapers/*.jpg "
QUERY="$QUERY$wallpapers/*.png "

if [ "$QUERY" = "" ];then
    echo "Oops! No images found within specified directory."
    echo ""
    $0 --help
    exit 1
fi

# Get number of wallpapers -------------------------------------------------------------

NO_OF_WALLPAPERS=0
for file in $QUERY; do
    if [ ! -d "$file" ];then
	NO_OF_WALLPAPERS=$(( NO_OF_WALLPAPERS+1 ))
    fi
done

RAND=`od -d -N2 -An /dev/urandom`
NEW_WALLPAPER=$(( RAND % NO_OF_WALLPAPERS ))

# find and set wallpaper -------------------------------------------

total=$NO_OF_WALLPAPERS

wallpaper_file="not found"
CNT=1
for file in $QUERY; do
    if [ $CNT = $NEW_WALLPAPER ]; then
        if [ ! -d "$file" ]; then
	    setwall "$file" "$CNT"
        fi
    fi
    CNT=$(( CNT+1 ))
done

setconkytextcolor
