#!/bin/bash

width=300
height=400
x=50
y=50

convert -resize $(xrandr | grep -m 1 "*" | grep -o "[0-9]*x[0-9]*") "$(rotatewallpaper -f)" "/tmp/image1"
convert -crop ${width}x${height}+${x}+${y} "/tmp/image1" "/tmp/image2"

brightness=$(imagebrightness "/tmp/image2")
rm "/tmp/image2"

if [ "$brightness" -lt 400 ]; then
    color=ffffff
fi

if [ "$brightness" -gt 400 ]; then
    color=000000
fi

echo $color > ~/.config/conkytextcolor 
